const data = [
  {
    type: "burner",
    name: "Linkedin",
    budget_name: "Software based",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "block",
  },
  {
    type: "subscription",
    name: "Mixmax",
    budget_name: "Software subscription",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "active",
  },
  {
    type: "subscription",
    name: "Amazaon",
    budget_name: "Software subscription",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "active",
  },
  {
    type: "burner",
    name: "Instagram",
    budget_name: "Software based",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "block",
  },
  {
    type: "subscription",
    name: "Twitter",
    budget_name: "Software based",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "active",
  },
  {
    type: "Lenscart",
    name: "Linkedin",
    budget_name: "Software based",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "block",
  },
  {
    type: "burner",
    name: "Oracle",
    budget_name: "Software based",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 feb",
    freq: "Monthly",
    amount: "300 SGD",
    limit: 100,
    status: "block",
  },
];

export default data;
